### ISSUE TITLE
RasterizeVector fails with a very large attribute value

### ISSUE THREAD

**Issue by ttislerdg** [ngageoint/mrgeo#123]
rasterize vector, fails after a couple of minutes:
15/10/12 19:14:33 WARN scheduler.TaskSetManager: Lost task 205.0 in stage 0.0 (TID 205, ip-172-31-52-89.ec2.internal): java.io.UTFDataFormatException: encoded string too long: 152078 bytes
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:364)
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
	at org.mrgeo.geometry.GeometryImpl.writeAttributes(GeometryImpl.java:120)
	at org.mrgeo.geometry.LineStringImpl.writeObject(LineStringImpl.java:187)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:44)
	at org.apache.spark.storage.DiskBlockObjectWriter.write(BlockObjectWriter.scala:204)
	at org.apache.spark.util.collection.ExternalSorter.spillToMergeableFile(ExternalSorter.scala:304)
	at org.apache.spark.util.collection.ExternalSorter.spill(ExternalSorter.scala:254)
	at org.apache.spark.util.collection.ExternalSorter.spill(ExternalSorter.scala:83)
	at org.apache.spark.util.collection.Spillable$class.maybeSpill(Spillable.scala:87)
	at org.apache.spark.util.collection.ExternalSorter.maybeSpill(ExternalSorter.scala:83)
	at org.apache.spark.util.collection.ExternalSorter.maybeSpillCollection(ExternalSorter.scala:241)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:221)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by drew-bower** [comment]
Is this a not enough bits kind of thing?

**Comment by ttislerdg** [comment]
Exactly right.  The method we were using for serializing attribute strings (writeUTF()) actually writes a 2 byte string length before writing the byte data from the string.  This limits the string to 64K.  The fix is simply to use a similar scheme, where we write the length as an Int (4 bytes), then the byte data.  This allows serializing strings up to the maximum size of a Java string.
