### ISSUE TITLE
ImageStats collection during MapAlgebra

### ISSUE THREAD

**Issue by panrufio** [ngageoint/mrgeo#15]
I have been recently running the crop map algebra command and come upon and error inside the mrgeo-core/src/main/java/org/mrgeo/mapreduce/OpChainMapper.java with the statistics built up.

The problem is around line 171 and 172 where the calls are to ImageStats.

I got this one first:

java.lang.ArrayIndexOutOfBoundsException: 1
    at org.mrgeo.image.ImageStats.computeAndUpdateStats(ImageStats.java:152)
    at org.mrgeo.image.ImageStats.computeStats(ImageStats.java:173)
    at org.mrgeo.mapreduce.OpChainMapper.map(OpChainMapper.java:171)
    at org.mrgeo.mapreduce.OpChainMapper.map(OpChainMapper.java:1)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:140)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:672)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:330)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
    at org.apache.hadoop.mapred.Child.main(Child.java:262)

Then as I captured the ArrayIndexOutOfBoundsException from the first one, the second one came along:

java.lang.ArrayIndexOutOfBoundsException: 1
    at org.mrgeo.image.ImageStats.aggregateStats(ImageStats.java:97)
    at org.mrgeo.mapreduce.OpChainMapper.map(OpChainMapper.java:172)
    at org.mrgeo.mapreduce.OpChainMapper.map(OpChainMapper.java:1)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:140)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:672)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:330)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
    at org.apache.hadoop.mapred.Child.main(Child.java:262)

It looks like that array of "new double[] { noData }" is probably the culprit.  I go around this to do crop by catching exceptions.  But, I wanted to check with you about this to see if there is something wrong.  The OpChainMapper has not changed since the initial check-in. 

The data I was using was the Kathmandu image.  Using crop with the Paris image does not start a mapreduce job.

**Comment by panrufio** [comment]
When looking at the metadata for the image that was output by the crop, the default values array contains 1 value while the original default values array contains 3.

**Comment by djohnson729** [comment]
This issue was resolved as part of changing map algebra to run under Spark.
