### ISSUE TITLE
RasterizeVector failing on roadways vector source

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#226]
Attempting to RasterizeVEctor against s3://mrgeo-source/roadways.tsv results in the following exception:

ip-172-31-57-157.ec2.internal): java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:860)
	at org.apache.spark.storage.DiskStore$$anonfun$getBytes$2.apply(DiskStore.scala:127)
	at org.apache.spark.storage.DiskStore$$anonfun$getBytes$2.apply(DiskStore.scala:115)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1250)
	at org.apache.spark.storage.DiskStore.getBytes(DiskStore.scala:129)
	at org.apache.spark.storage.DiskStore.getBytes(DiskStore.scala:136)
	at org.apache.spark.storage.BlockManager.doGetLocal(BlockManager.scala:503)
	at org.apache.spark.storage.BlockManager.getLocal(BlockManager.scala:420)
	at org.apache.spark.storage.BlockManager.get(BlockManager.scala:625)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:44)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by djohnson729** [comment]
I suspect that this is the first time we've attempted to rasterize this vector source since the conversion to Spark. My best guess at this point is that there are one or more tiles that require more than 2 GB to serialize because of either the number or complexity of the geometries that intersect the tile(s).

Currently, we determine for each geometry which tiles it intersects, then write a new RDD with the geometry repeated for each of those tiles. For any given tile, it contains the entire geometry of every feature that intersects it. One possible solution is to clip the intersecting features to the tile, allowing a buffer around the tile for accuracy. Clipping right to the edges of the tile can lead to edge effects.

**Comment by djohnson729** [comment]
The potential solution mentioned in my previous comment will not work. It might reduce the chances of this error occurring (by reducing the serialized footprint of large geometries), but it won't solve it. Since we are duplicating geometries multiple times (once for each tile they overlap), the original number of partitions from the input will be too small, and that will result in too much data being stored in each partition.

So we need to re-partition. And the safest approach is to compute the largest serialized size of the geometries and then divide Integer.MAX_VALUE by that value. This yields the number of geometries that are safe to store per partition. Then we can divide the rdd.count by that number to compute the number of partitions.
