### ISSUE TITLE
NullPointerException while exporting

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#285]
In EMR while ssh'ed to the namenode
 * cd to your home directory
 * Create a sub-directory in your home directory
 * Export an image to that subdir using "mrgeo export -b 42,46,49,52 -f tif -o mysubdir/ -z 12 -v s3://mrgeo/images/myimage"

For each tile it attempts to export, the following exception occurs:
java.lang.NullPointerException
	at org.mrgeo.utils.FileUtils.createDir(FileUtils.java:73)
	at org.mrgeo.cmd.export.Export.makeOutputName(Export.java:625)
	at org.mrgeo.cmd.export.Export.saveSingleTile(Export.java:169)
	at org.mrgeo.cmd.export.Export.run(Export.java:496)
	at org.mrgeo.cmd.MrGeo.run(MrGeo.java:247)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.mrgeo.cmd.MrGeo.main(MrGeo.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by ttislerdg** [comment]
I think you might  need to remove the trailing slash from the directory name.

**Comment by djohnson729** [comment]
The exception occurs when specifying a relative directory name whether or not there is a trailing slash:
<pre>
mrgeo export -b 42,46,49,52 -f tif -o mysubdir/ -z 12 -v s3://mrgeo/images/myimage
mrgeo export -b 42,46,49,52 -f tif -o mysubdir -z 12 -v s3://mrgeo/images/myimage
</pre>

It will work if the path starts with "./" and ends with "/"
<pre>
mrgeo export -b 42,46,49,52 -f tif -o ./mysubdir/ -z 12 -v s3://mrgeo/images/myimage
</pre>

Specifying an absolute path always works, however, it behaves differently when there is a trailing slash  compared to when there is not. When there is a trailing slash, it writes the output files to that directory. When there is no trailing slash (even if that specified subdir exists), it writes the files to the parent directory, and the file names are all pre-pended with the subdir name. For example, if ~/mysubdir is used, it will write files like /home/myuser/mysudir355009-346-705.tif. It looks like it just appends the computed file name to the end of the value used with -o to make the file name. If the value of -o is an existing directory, I think we should write the files to that directory.

**Comment by djohnson729** [comment]
Export arguments | Pre-conditions | Results
-----|------|------
-o ~/test | ~/test does not exist or is not a directory | Multiple ~/testtile-* files written, one for each tile exported
-o ~/test | ~/test subdir exists | Multiple tiles written inside of the ~/test subdir named tile-*
-s -o ~/test | ~/test does not exist or is not a directory | one output file stored in ~/test.tif
-s -o ~/test | ~/test subdir exists | One output file stored in ~/test/imagename.tif where imagename is the actual name of the image
