### ISSUE TITLE
Slope operation failure when source image does not have tile data in top-right portion of its bounds

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#76]
The following exception occurs:
`
org.mrgeo.hdfs.tile.Splits$SplitException: TileId out of range.  tile id: 8062783.  splits: min: 327554, max: 8062782
        at org.mrgeo.hdfs.tile.Splits.findSplitIndex(Splits.java:154)
        at org.mrgeo.hdfs.tile.Splits.getSplitIndex(Splits.java:130)
        at org.mrgeo.hdfs.tile.HdfsMrsTileReader.getPartitionIndex(HdfsMrsTileReader.java:428)
        at org.mrgeo.hdfs.tile.HdfsMrsTileReader.get(HdfsMrsTileReader.java:314)
        at org.mrgeo.data.MrsPyramidRecordReader.setTile(MrsPyramidRecordReader.java:853)
        at org.mrgeo.data.MrsPyramidRecordReader.setNextKeyValue(MrsPyramidRecordReader.java:784)
        at org.mrgeo.data.MrsPyramidRecordReader.nextKeyValue(MrsPyramidRecordReader.java:645)
        at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:542)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:151)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:773)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:170)
`

**Comment by djohnson729** [comment]
Fixed by commit e37ec4947c1660b2926e5245981dec9d10da586d
